name: Dependency Check

on: [push]

jobs:
  verify-deps:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install pipreqs pip-audit

      - name: Regenerate requirements.txt
        run: |
          #cp requirements.txt requirements.old.txt || true
          pipreqs --force --savepath requirements.txt ./goose/

      - name: Install updated dependencies
        run: pip install -r requirements.txt

      - name: Run security audit and fix
        run: pip-audit --fix -r requirements.txt

      - name: Commit updated requirements.txt
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add requirements.txt

          git diff --cached --quiet && echo "No changes to commit." && exit 0
          git commit -m "chore(deps): auto-update requirements.txt"

          git push